package com.qmr.news.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.qmr.news.model.entity.ChannelEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHANNEL_ENTITY".
*/
public class ChannelEntityDao extends AbstractDao<ChannelEntity, Void> {

    public static final String TABLENAME = "CHANNEL_ENTITY";

    /**
     * Properties of entity ChannelEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "name");
        public final static Property Order = new Property(1, int.class, "order", false, "order");
    }


    public ChannelEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ChannelEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHANNEL_ENTITY\" (" + //
                "\"name\" TEXT," + // 0: name
                "\"order\" INTEGER NOT NULL );"); // 1: order
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHANNEL_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChannelEntity entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
        stmt.bindLong(2, entity.getOrder());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChannelEntity entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
        stmt.bindLong(2, entity.getOrder());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public ChannelEntity readEntity(Cursor cursor, int offset) {
        ChannelEntity entity = new ChannelEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.getInt(offset + 1) // order
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChannelEntity entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setOrder(cursor.getInt(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(ChannelEntity entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(ChannelEntity entity) {
        return null;
    }

    @Override
    public boolean hasKey(ChannelEntity entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
